apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
    namespace: forgejo
stringData:
    username: ENC[AES256_GCM,data:1S3Tp4hSKP/wM+GBZA==,iv:g71Hfs8A0xTpdZ5UdQPIufx7XCWtoNJW13y6b/k1+DU=,tag:WxaUVHx9JeDKHwashtfHCQ==,type:str]
    password: ENC[AES256_GCM,data:2Ro7PBCPVTCM0FYMbyOPo7ti3nU8SFrlEdQvvQ+8lA==,iv:i73p4wdYEPsYoCxbYM5j+nD7rKGH9JX5y7pGDrHFOvg=,tag:Cm+vhRmhBaDAOQYGZUakGQ==,type:str]
    email: ENC[AES256_GCM,data:t2xqnU+c493H+tXEPp9yUd3Vvr+U,iv:Gv9mjtzGH9bRMPPs977XQ0Foy5bDfV3slrdBlXhYd0g=,tag:2hbVUraqsFmFrpJdaBwRUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaWx2Q3p6Qkl2YkloVUFa
            anFvVm5ZTDB6WGhBNXAyemdNc3VyMXNHK1VvCmxNelVXQmxIQ2p2cGJWYnkydG5j
            LzNSZW1WSWNwOXJCb1Z6NExzTUt2QmsKLS0tIHFTSk9ybkk3VDBBdHBFTDZqU09F
            dGMrclo4NDRzbzVLTVVNaWJMR0VJWVEKOsMxXg0zg4jcy8hNaicGMaIjbDgBek3y
            MVd2Bcr6RULkog+X4u0e5cBTQNtSr2n4EeqbV4srd43b8bvFcTc9KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:58:55Z"
    mac: ENC[AES256_GCM,data:YyALwRi2V45OlyARKdZEm/ASeWvqR8s+bWlCQnyWhzH77Le/MsYziYRYQ5FX8/Eq15jyaXpWei9h1Iw1X4XvW1yUMa9M7EGzXmMHS44nMPFZ+xKaM1VUju+stU6283Nyo1xvrOpTM5iWyaUDNsesZODpvS5W4woEzkIE1LN59fI=,iv:wyNAX8KcbxBLznGx3VZS9DUTofOYH6xhRKUwJ8w1Hds=,tag:5HWSRHWp7ICNqFOroKW2hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
