apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-cluster.yaml
  - admin-secret.sops.yaml
  - helm-release.yaml
  - httproute.yaml
  - tcproute.yaml
