# SOPS Configuration for eh-ops-private
# https://github.com/getsops/sops

creation_rules:
  # Files with explicit .sops extension (excludes .sops.yaml config files)
  - path_regex: .+\.sops\.ya?ml$
    age: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c

  # Secrets-related files
  - path_regex: .*secrets.*\.ya?ml$
    encrypted_regex: ^(data|stringData|password|token|key|secret|crt)$
    age: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
