apiVersion: v1
kind: Secret
metadata:
    name: axonhub-admin-secret
    namespace: axonhub
stringData:
    username: ENC[AES256_GCM,data:/Il0S7I=,iv:H7+R4b3yiP8Nj8MPus89KNFrh4bitV+ZnVQkyAuqreg=,tag:xQKgmf+uT3Iqe5x0rI/bLg==,type:str]
    password: ENC[AES256_GCM,data:6ocKzGRzsn01HNG7x0sI1tKCUqK3mLE+983Fr2d7Thw=,iv:C9rI2ABOsc3AizoFIJNP3Cqn6kGS/QFJ6bymoDYbadI=,tag:qSU5vBQ62ve8a6LrwUIkGw==,type:str]
    email: ENC[AES256_GCM,data:qHI2/luzs/JnktJEqL3WQvMpqBt+,iv:5B2/7IZUoWYs48rqOFMuSX4++ALBqzP355p05ZCGMsA=,tag:OyUlNiIREVKsbWcLArGTmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWo0UFNzK21IUW1UNkd1
            STZickpxWld2U215OUlvT0x2TjdBYXdOWUVBCmFMS1A4Z1V6OEd3UkpiT0JLQmV0
            WDFZN0N1MldkQnI5Wm5uNkQ0dTlPbXcKLS0tIEI1S2FkckxkcnN0R0N1RU5tcnkx
            cWNTNkV2ZHpBemJjTlEyNUVpYzduS1UKAnUKnqp28g/xLDCKMFfgUoNETL/lKjZy
            E0bsjHDH0ks42Pg3aZFfQCB69o/U/49rWRBg4+9aGcVyMzKhbeRnGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:29:38Z"
    mac: ENC[AES256_GCM,data:OrQXO6cvyhEtLW1WwYIiqaUzDpMBv05UbmkbkQKk/4Tgbz6elgaw3ZByceps3SAlH0nEX+E8d6FIN498YUwRxnnXsSr93ECNAhIbV7z9ab/fKBkFqvje98BpIarxgwnTPbbyrL7oX6PDyEaU4ioNJlbXokP/J8pSBXBWm60M85k=,iv:MyhcrgwBpLusmhAHIZPAdKE/NvGz8XFix+2NpaomjKQ=,tag:KaVdBOKQ36SI6sV0TtyWlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
