apiVersion: v1
kind: Secret
metadata:
    name: autoanneal-secrets
    namespace: github-runners
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:x/S1f5BlRnAlF+rqWtSCu0SYUeRPCkj/OIJ7hOVHueHybK9A3gEb8M7JsprG2MUx2g==,iv:qxknpFbtGwHADnzjbTui4oe15c241bR6LtE6bA0XqAU=,tag:b3slh5gY6cQeMgyC+CZhkg==,type:str]
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:+1TOXypDKx/b8jo0CQhaOsmK7zVp3/6kkz9+qvh6NKfzlqs0EGgzG3CEgzV2UfHhHA==,iv:561sxgke+lWFRRwLDPYXVQb3VV9Qc4csU7kdf8MSKl4=,tag:3+qwhyweeZW0HfaqG32o2Q==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:+PZ86zeVuxnNKZPNU8W3RSuBvegy8JYQ7+w0QXZOkeVY8f1U0lYFKw==,iv:M7PuU1tzoFnpku8bLblNDg8EeRIJw8yTdrtpi5QuFWk=,tag:3VUeOPlUItmL7R1CXz50SQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUm5zcktPMzFYMEZ4R2Ro
            SllZdEtzSktMSDlEV2xZUEVSNGNXSDRvQkRNCnZwbUxqMlpsOUNJSVp2c0FUZ0pY
            aS9XUHV3RlZXZTFuN3p3eUI1RWVEOXMKLS0tIFp6QW5DZFVQbUxYY3MrOHFQOEJK
            ZysyYnZPNENnZzR1L0FTbjhZSDNCZnMKbqbJ8JZo5NeNWRWvDDOhJCMOLsy4MHVL
            fJ8YD+m/1FtwHdUzR/bjDPPzUcNtoXiCwYPrnhmnIOqF6k9bwqb0Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T02:34:52Z"
    mac: ENC[AES256_GCM,data:JDLjoLMOC2SeDVpj+RoOxFAd6MzGI525pUArglREcDtESQxlU/efMO6niZcs+6ZuoYGNc4S5fNzxjRve73ubTRIxfe2XMQFz0EUm1Npkt5PuWhfJK4bkxijv1TDGUGjXArrwQPN8szS/wf32ltwKgvhA1+gNLxwSQX9OCOuUP7A=,iv:bbwZE6/4O28R+BAA6tqBu8ckZaPjeFlR9xlSj3riiCU=,tag:6CmO1fUvUsGs9ODG+PUMLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
