apiVersion: v1
kind: Secret
metadata:
    name: autoanneal-secrets
    namespace: github-runners
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:OkfHF5lU9f9vsuI04R5Ic+q1lb6OcsuOsUvrOiRMsVnOJXEU6jg2YgkqejlVb3e+qD2T,iv:bGoA5tLkh/suQfH0zzS7PJY4CvQrtJzHkb8FYkJ9iKM=,tag:Dulb8rMmC9GWeNBG0KG3hw==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:vXk9MltcY6xwrxo1YnOgJMO8eQEP0lgIM7g7CVEyDVC8e5q3dMOQgw==,iv:dRVIboBsLcaJHoitbNW+/kJd+Y3VQGt0WsxoPupzpJg=,tag:gEglUhdPDvsHeDG2Bil4GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WUdJVHVKOTlkMFFXcnRF
            anQ2Ny8xUjVCT2lMY0tjc0VrMEJjNDlRaW00CnNoY3dWQVZ2MkJWWUYxdDBVbUpP
            TCtOWE8yVEtpNnVQaXJhWkNyc1kyMmsKLS0tIHpEaE51ZlUyV21nRFpaZWg5MlIz
            a1VDT0pjZjhWbEVpQUtPSGRiM1pDRnMK4PM8yKc192+WxhHpzGlBwV0gxs3YTnO8
            urRjvLeKQJusj8VPizLNEd608ffi5OA8hOPljpT+G3MxSURTKS234w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T03:09:24Z"
    mac: ENC[AES256_GCM,data:ugmXYlICZtt1iorZWB00ZCHBrtWJBTGt2vryWZ+zcVH/A/U/sN4ouv89yHSvl/lhkv6tiz4/ml4CLTCbxnZ7gfvjEYllNE2l0hthO1wbR3T3IAXFsbNH+b00Cjx1r4Cccowc18zAkQzMOTGveoV5PeyRlh3p84vaWoeIKE8a8jk=,iv:XNIXNiAcme97q0mVyROQZv7EMmuow55YCGr2nmRl+AA=,tag:zFYWqHxkdkoolZkoaaHN0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
