apiVersion: v1
kind: Secret
metadata:
    name: autoanneal-secrets
    namespace: github-runners
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:MijrORB8LufUeqkGanCR3TXQeTl605HuxaMaXiEPNr1XrmH+fMYdjq6ObWjT74HJNNjh,iv:hFYPQOcj8ZFpAyDuJs3cwcSgALgbBkcvijb0sS9WXVo=,tag:6wa1dR+7/CY66Y3f4+cseg==,type:str]
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:CM/vr5A6Bb9KGDDVI7FBm9vJos//NP38+hM5IWTZJiF1A7HzubizNAsgVbsqYlX4uAhD,iv:Os5eFKXN1drtg6FTg+PRdo4k5xvZqJGZBn6XxCk3vIc=,tag:cCAqPWP+Qdg5oz5dUt2BEw==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:tFI4156R2P/HjjOxdohsBm5iBvBgjMEZYiPwJPY4wdGt3ju0Mbl2gw==,iv:gcq2kMoRGtgdghJrZ1WA6zRE4n0G1VkAi5sA4IjNbwE=,tag:WvVf8ROmAV7LlqjjcbrfBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZTR0UXVZWmwydnd0NGZl
            QXEyQ0dBTEVEQTZGUTBkOUxsTUplTkVIS3pJCmRXeUhlbVhvcHBkcHlWZDNtZHVV
            UW9TTHZhV1ZPZDk5WVUvVWxHOW5vOGsKLS0tIHc3R1lwSS9xWHI5bE5OSThCTTNu
            VXNEKys0V0d1UFVEMDJrcGRHY2FNSUUK+nOe4t/7llFVkXslqKqJz/AKh2bByMFZ
            /IlwF8tOj9bVxatusZPOnb8Flcvjh5dFt2mWAT3X8XEShoGRKPTlJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T12:58:46Z"
    mac: ENC[AES256_GCM,data:hRwcbM3kBfWMjbwvqIg9BYB9zxu8uQh22cG7wuBl7vLOsM5Mp5sZw929TqX7q7XFyhckW2/Wwb+Zhm8eawmkdNKV2RsUjCSPflEWqVLKbLcmAgmswmoIGjMLFUNsFSVtIYPLPPwkxMVXOa6pYsY3NwWg/QQTxnk233R11vhgWKQ=,iv:v9OiG/1zyH/NOtQ+CeqNkPpJskLHh7CfzSFK4yVgqHk=,tag:5KlvoTMo8P2wC9UnuZ91oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
