apiVersion: v1
kind: Secret
metadata:
    name: falkordb-auth
    namespace: falkordb
stringData:
    password: ENC[AES256_GCM,data:kRZffNBbhtqo8qcp1nvzeZdEaPA0kaWQypvjwp0vJ8c=,iv:i783MxFutn7456B7kIJ5fT0lXj4DrxSmeoEOb8oMHdI=,tag:jCFMh5tyi1ikPZP7PyKS1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUW1yMlRsMzBBdTZDRzFj
            M2NnSUVITFZLclhaMzdtOUQ3a2FQUnlIU0RzCjNSZnNhUEdkMGVhOXJsUzA5THNY
            S1hzcCtkdlF3bmF1OTlXeE9RaVJOaEUKLS0tIGF1dWJBQVpDbjRtWjBiSkRKVHVI
            aEwxbkJMVVREUzBCbXZ0SUJTeUZzU2cK8+kWyv65Qyokc00fWP0hvtMavn8gQwL0
            sIrjVvZ9si+2bk/l3kJrs+zlHFwvu3hyu6t6wlZtiUJ9EXd82C6nvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T13:22:52Z"
    mac: ENC[AES256_GCM,data:z7GTaxql+gqjyxq4BvUB1JHCnIiTZtvLH/R4pyV7xElMQ1qMP60nDTa8bRomfs9nuB/dsEsQVHH4cSSPBC/jyQ9aAXywiO9zKzDIuLqnyRqXH3+DewOrXBH8CehkkLjI9vIhXz38NLPtIQr09kcJfOKCq1Ztt1HwkB4DjA1J4uM=,iv:UHHMs1/BHr2S43ZSANiz36cJH45KtBauag7VukKHJdw=,tag:eVGKHHbQRwbW+HO4Mt9Ikg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
