apiVersion: v1
kind: Secret
metadata:
    name: cnpg-admin-credentials
    namespace: cnpg-system
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XrcSzhL7z38=,iv:I8ixGFF7A0cwIPRSUtn+/YDz4L4yYV2uTqq/aTB0EoA=,tag:W2A7FVmHBb4/IY1aEcPxXA==,type:str]
    password: ENC[AES256_GCM,data:QrUr+VIdAylCSgp8yHmON61KKmvQamNGsxaPxM6ueNI=,iv:0pXwVEduOUm3fC2/ZxT6apNz11mHQTIgKXY4g7EWZYo=,tag:C743jJfUN7AmdXKbwBLMgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUHlVYVcrS1hCUS84RFlm
            ZE5IRGU1NG9naCt2Z1dsMk45OHE3RFhZd1dNCktBT3Q1T0VCZ3BEVktPNTIvSDdC
            SzZiME1SdVlFQXVwZm5Ha1NUbW5SR0UKLS0tIFQ5K3pLaGhLS1ZHWnFrdUhuNUxa
            NjlTa2tKU0M2Z1EwNFQ2Q2VNVGhlbmcKmTpYA0BGyd7gNbUdCxrxXRxiFli3Zila
            apjEH9/eHvRAfWNmLeOrwc6jj8tT7U9thyJegmPulpf//JwVTcvsSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T12:40:34Z"
    mac: ENC[AES256_GCM,data:mt2/cpQFEvSH2aUjowU9gOXa1QUvWSlR5/yD1E/dns9TRgaClk5XcAaZY3uAO0h62d0MSJ4xD4yhvxlik7Lw/B3axaRHafLKPldJl74sGQqbHRZPvAvS/ikHdPi0afrzliJgqyUAcCf8MYPlk+DsXr1p8ROPTXUGD6+xJV1CrXo=,iv:FR8VjCuIo4n1Q0M72Blr8Z+XjGqqhv2uL/UhbRYj1qI=,tag:+e+SOKCvES3D5D8He4/Y6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
