apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plexus
resources:
  - namespace.yaml
  - db-cluster.yaml
  - secrets.sops.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
