apiVersion: v1
kind: Secret
metadata:
    name: plexus-secrets
    namespace: plexus
stringData:
    ADMIN_KEY: ENC[AES256_GCM,data:kr4zhTTmmnDd9tcNq+Cs9VuZdTL5G2bF5jkU0vhY,iv:CEF+uK7wY0bfg9gaUtLuDMoWeJ3GuSTXJzcYIBX/wz4=,tag:NwhqZQkv/xXZx3WwKxahDQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:37fL2Kn98+bdJ6pzIREQXSxjgPVYiMASfUjIqaRqPETsAQm/Xa39vZAFbznkammMfa+fyWhOw7e6igTXMFO7Qw==,iv:u63kNnAJj9C3ZA2mdpJ5tyKvibStchOnTvsvuixAV9A=,tag:qMa67bCJ+ZXcjp/P8MFwiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVEd4QzJPVG51NE1rMHlm
            ZmEveTk2VlgvT3dlc21SRnh4OVV6UWc0WjNVClN2VGN0VmdkOCt4ZnV5aUlFR01z
            TCs2aUkyVnJMc3VvTVkzc21nWGpVeDQKLS0tIEdZd2oxQlJ0TWhwZi9OS0h1UHNN
            QzFVbFFmSkx4NUE4d2FpRGlPbUtmU3cKZUXSfzijdktc1XhBzFwZIB6FAZe4KHNv
            8wDVNxQGOq8HUMdNwLVGbts5JYzLl+Vj0WGUuW/MBc+UUWD9Dzf6Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T09:13:37Z"
    mac: ENC[AES256_GCM,data:cPodZS28TC3ju5mLbUWSn8b5YmPcVgEpQEbCpqBZmn3Z3U+Wb3WVRS7sEgyI5h3JWEy3TTZJhTwB9acUczUuRcq62l0hmasevAjV97N40mvbEaUsLKeozDgFQu/fgdMcUfpJyAaF2o12SkSYp/myfx7tptnev8SZ78GMFmOUb14=,iv:Cbgd7//HyW++6U7LcIx8ageGWgKg8iTCai2cc+vF6lA=,tag:U8UbslHV2qIWoONbSXTPYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
