---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-data
  namespace: forgejo-runners
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
