apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-token
    namespace: forgejo-runners
stringData:
    token: ENC[AES256_GCM,data:aeyfB/fgP8x1KjLeK9OkY8oa8+zQFjpcFzZHpaF5AgKXofAKfOfOdRafUA==,iv:zXpV5tGu2+PUSE1/5Qi8jq8VrOl6rv3pBV8+5hOKaLw=,tag:q/0ebZbtg+DbGdtwcwfQ7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTXVnaTZQUWpTK0l3UFd1
            bFJ1S1RCM2N1VU4xQXpaYU80cit0KzZSQVRZCmtMdkFlaWh6dU96MTVsc0ZPdmRw
            WHJuTnpNUEx6WVFEcjJpSHpxa1lueUUKLS0tIEdheXlvT2NHSFliUWxsdGRqZlla
            UUh1TmdtSFR2eEZYZGRnQitBV3kvRGsKTbo/EZJ7DvvQS3uWrehYXrp/drbTYbWI
            pq8pnQURa2Gqqq3UR8tOwWCP/78y0Rt9dDRE+azGBc54v20GHvmWpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T00:09:18Z"
    mac: ENC[AES256_GCM,data:Je/7rGDYAfEDKhJEyrIEfwdwNqVeAeWy2F2iuz32KvGBs77g5PY4kZ3yxDNzkV0JkmFAL1Wp6SNk3DzCZSoOrlmuQNJ7GJ+s0+y4hr1QImBPx30dzYQcKthtFj7y6+9jtgsN8potO62c94gj4G/9vfnDFOs1m8hf+KmUJZ0ASvM=,iv:M//ia7SookT8MlC7vU9Hz+uYXZ5HPzEUFc2btB2jQfU=,tag:oODcXIEKWeI1cRzCL4EFnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
