apiVersion: v1
kind: Secret
metadata:
    name: inference-api-key
    namespace: inference
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LfRTVuWMs1QMOFfdLLKAzPUuOctRAnJuwzHVTAlAK/LYHdn+cWJnTOzkRwzt+uMiUIooiH+zEsZH,iv:HdElJkuvSeuWVXLC4+CwFaGIkJ8Cn6LoJhxKfnSW3lk=,tag:LUg2PgqDfU0ya4s8dzi2kw==,type:comment]
    bearer: ENC[AES256_GCM,data:Q5/R2D5fz0uWrFbOkstEeDaoX0WfPCkRSnxZMXpJUeV1cEX2d2/NHapqLAx5CnE3y6zkXEHl,iv:B5x6vyWfevqn4wy4VivputsXEoiy1meT60Xv/x+lkqw=,tag:E8MCJGrEjXmDpR+OSNz1Vg==,type:str]
    #ENC[AES256_GCM,data:U2x+Z6rT1hk7eHN3S/zo57a6GWH0RTVl0DDlRjY+h7ZnL58oteUFiGc6qqIugw==,iv:dI7/btI2+vrMVBUIsuAXb0qIGaGPb8VmoMw/2O8qAr4=,tag:bXdi5uk2gUEnHCUV9F7KkA==,type:comment]
    raw: ENC[AES256_GCM,data:hwdqlsrsb7jqWGJqdY2FPt8mu+A90q5hcUDhu9/5tx+GyVo5xFBaAL038T9QOho=,iv:/uT42KkkTWOoYPYN+iyltwMxwPOUzHbc6XhTx9QUnI4=,tag:+uagXG2Oy56v5bgvV5Jdwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RklOaFB1SE5xai9CRkFs
            TGdYZkR6SHNic0todWt0b0ZoNkpLeFpydzNFCit5Y1N6eFVMVU9Oc1NPVnBwbHJw
            ME4zcnFOdmE2anQ0aW01TUlLOXB4Q2MKLS0tIGxJZFZ5dHRQZGxIT0dJTm0xZDF2
            MGVvSVRZa284dDdGam1wYWF5SFQ4RkEKn+SPNl9sYNwckWrMLQQo9QX9a1W/B6T4
            JNIr98hz7XvjbD9IGzQPjFF9M7Ost6alV3L7xqktaEWiN/ZoIyilWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T00:25:05Z"
    mac: ENC[AES256_GCM,data:QDbEr8N2H9zJquJH+6klKRRss8b0ugnFNzCishDRuKAePs3+/PwHbwyr+ZJFoJc+ylxB8TP3GIm5lNtthv9Dt+aDzXr2kEDOpqSycuqF8mfxkW48L6usbHFcFo6qWQQPN8m3lJRd4j6C3XLpVcviI+6oajlxdTkD/SwnTBsBVqI=,iv:VqmMv07SQtZpR4NeDrcb6E6owsrFqOfZT01QAzW52eU=,tag:tChkQVdJxHlY4YRmJgj3oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
