---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: subnet-router
  namespace: tailscale
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 500m
            # 128Mi OOMKills due to Tailscale memory leak — observed peak 85MiB+
            memory: 256Mi
