apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    DOMAIN1: ENC[AES256_GCM,data:dZetPSUFmKz9ILRCiCn1,iv:6RwSxP7cshKD9QfGzM/H5GhOXKRtle5051uDwYoYWiM=,tag:LADaB7nlV6VSposItIFu4A==,type:str]
    DOMAIN2: ENC[AES256_GCM,data:N58zG5wJrvunFlrx,iv:6yd1auZtFNUud1l4fbENJ3pA5PRjY2Xzs3TOd6UmT/Y=,tag:Bt398ywcPffsZZxpFuJwCg==,type:str]
    DOMAIN3: ENC[AES256_GCM,data:WLAi3XL+A/4TiWIlZ2ybvQ==,iv:pz0PdJEqTbDSR9PI62U4SkaGQPPg8PYYjbPsaT+NyEU=,tag:Jmpjb1Wu7NwusI+V9Lh6wg==,type:str]
    ACME_EMAIL: ENC[AES256_GCM,data:M37FGzHHUbm3lw2XWk0e9VGvwFYh,iv:K8xhVX2fEWHnPgbaMB8yVKVUaCOMQFPQhHV0tctBcZo=,tag:3mm1n7AF1IthzCHFSvmu8w==,type:str]
    #ENC[AES256_GCM,data:+sw/uIv4T+9mXj2YnwFFtlCnlb/SNZPwznbQnnRJktj6EejZdCeuvGQ3SxWgXd/A,iv:LoVzfZmHrM6wHWHiPIbeLuYMRBNO/6aA1LRDmMPqR+k=,tag:uSCGms6cqrx5L0WzeWErLw==,type:comment]
    DOMAIN4: ENC[AES256_GCM,data:jU/C/cKd/VxcKozU,iv:k0C4owocQ0aUB1lVR81VnBPZT6eWR91dZyHHJunlNWk=,tag:BIwCZTKLLZFxCxerMrJOrQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:qkKWazfJjdrmp0w=,iv:NOMYkr3awSEOBlQIdPB30A/enT3+DK3KWzvj5+GLUWo=,tag:HWBSHB2zTRqwlicdaQN6LQ==,type:str]
    NFS_PATH: ENC[AES256_GCM,data:TLDslOzwHp0ezgqI5SqAph7b,iv:UoWjmxMDobGLKg3GAuxKjTKZIzaD5uS7wJ64+OxvKPc=,tag:vgETPst17iz2DGnxbz6/pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL3RkUnpGbi9zeTFSemFU
            ejU3VjlvUERNdVRmVTZJcVlYRkNwMlp1NUVBCjliRjBkY0V3Z01SNXh5cDc0ZThn
            T3JMaFBGY0J1TG1xYncxdjVBOE9tVm8KLS0tIEptSGoxczNwMDNjODRFWVZ5WXZz
            dzNJUExQU3VRc1hmM0xUR21Fd2IrRG8KnQOxqZwVmW8wLKTevgURPej6mTsa7GMZ
            Krkm+0MK5wzI8ySIfGaUtoXN46CJlXC8LMM1oT5/7U2U/Im13U56/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T08:46:25Z"
    mac: ENC[AES256_GCM,data:43jkNA0hqdkrajnJ9INTNdOAyka/LEyTME0rHaUJlw2eHWyHo337OgWKeKPWflJFlM0G26TakVe6+WISBZ8loqMX7mgVYYPlKKOxxHIrR/McupsOa2oObLGbdd1IUAK2Pk01QWmOOJZOq9Uv0TCkrfaqXsdAbSDEpIuaa4pk+M4=,iv:m4dN8v7cpMem8HNdXmp5pwIH2gQdb+wymkUD/Bn/1kM=,tag:gR5UDJXLKfrVadO/KuG+uw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|token|key|secret|crt)$
    version: 3.9.4
