apiVersion: v1
kind: Secret
metadata:
    name: ghcr-reddit-gateway
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:n3l2H/G5bvD9Tp4WW2b5/MKU1wUaHnZVJsfcpLulpVKZh6CbZIGtRZxy44w5WsNQkuOzsHd5Byv4j2Oa+8TW+i7ECQZ/OOPJcLI+UZv2pALItTUZPoPUMnpY0uciRSRvFOYAiDvWT4xBQUH+2ojDZPjqOIAaPqT4SdfCjfIHvZQL/T2VT2dQZ6uLaiZmztPlI3ExpgetRgsM3VvKhynTOtL1RX3cq+lQPEu6+PV8Ca8iq79dwVeUJS9adBkIGzu2,iv:fVGi5Xkd59lZLBELRcRnUk0M4w4y1Z7QFWu9AR8SlIM=,tag:Y3eARRMw0v0GcbS49ntKHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbEZyNk56MUllNUlGWkYy
            OEN4OXpxNUNncE8xOE55ZEw3a21kZklQOGxJCklWNU91eE0rWUZSRVp6WnFMYWZ6
            QlE5cGNOTnNKdVNUK0NDT3NJckR5YlkKLS0tIGhMVk9VWWFySlI5SnVQK0h6MGNk
            bS9LallrcGhWeGJyTG1Rc2oxRWJCZFUKn/MMjW4uqfsjHr67KnPTCNOCJJBIx10i
            ZVCdpEomgwRczPGyyQJ37zr7bTWLmpXj1aMB9ElLbtM96b42eVytgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T02:11:59Z"
    mac: ENC[AES256_GCM,data:/Rdc2RnvUmnGFPVfPb8nx1l6YuelFnN8/H1jkT78uPGX1fEYoV22zmj7jL9nt0Pr2kG4iNlrCA0jEiTFfq2ZAU4LSyspgnurHVAM01/aFCCx3gzG1nqjWSj4kaaKlvQG3FY0CXzNI/MJSx9QxHQGt370bel7TqCT/HfwokwJ7Jo=,iv:ffO8DNIhCxjx+KCe8YxPYOSeQG3KSeUC56CLSR7bAco=,tag:TJ4JS8xNmF2HKTJGUWXS6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
