apiVersion: inference.eh-ops.io/v1alpha1
kind: InferenceModel
metadata:
  name: glm-5-q2k
  namespace: inference
spec:
  backend: llamacpp-vulkan-moe-flash-cpumoe
  modelName: glm-5-q2k
  nodeSelector:
    kubernetes.io/hostname: shadow
  resources:
    memory: 30Gi
    memoryLimit: 120Gi
  env:
  - name: LLAMA_FLASH_MOE_METRICS_PORT
    value: "9090"

  scaling:
    cooldownPeriod: 30m
    enabled: true
    evictionPolicy: Default
    maxReplicas: 1
  service:
    type: ClusterIP
  source:
    huggingFace:
      contextSize: "8192"
      files:
      - 'Q2_K/*'
      modelFile: Q2_K/GLM-5-Q2_K-00001-of-00007.gguf
      repo: unsloth/GLM-5-GGUF
      tokenSecret: hf-token
      tokenSecretKey: token
  storage:
    modelDir: glm-5-q2k
    pvc: model-cache
  tolerations:
  - key: amd.com/gpu
    operator: Exists
