apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:rkg0a+FP4NbcRZHcsk9xhs6z5rCqlyer+q31TxB9tjXUhhZJmdJSH66gwokCM7VoZSrEAb3NOylW4BXtBJeETEQgjP2Pru3TKZ0Bw9XinLmRXnMoCoZF5OSq1rHM4OSY9ni/kNnrTdyF6wMqqYrmbGGziiNsnBsfREPdUf3LPQ3OaHxPqaC4Bci9Mf2qKcrcH/7amHIZLPAMiPte35/NVeVCUNyrjkhLnfV0RARNvvndRZjladK4fhxIElTrzo2Vcw1sWtGGMLSbRaKC+UHv8jFADarcs/ia2vJCycBPFM4RyR4/DnplZz4wY0LUIRo13Aze7T+oEQDowwfQn8yYTtk0jBZX9xhHJjGFKHveii/jqHeEYtRYd466VoipKT9p0Ivm7LbsNb7sqypHe5QL6rBTtlFM7rnZvQD8+CUp00DsAGr5xgMR5ongd7ZSdbEakjkQwt88LhfhspoTNYU6i9o6XuC4OnrljfQr9A2/bLx+sevcoMSlVGypIliAILcC/lurMevBzVOW73+75tg+oxJbtzIIV9ddQ1yFB+gGJ98FaSH/Bft1xy3I8XqnWpu4yFkWTU9FRzUacMXVvP/q3OYeHe7AzFkMnD6D9UVOn9n0sGR8VQPxpwLPRLLTBD8hvVz/vyUp6yIF2lxYVTGRnffr+V+9hwHES7fJjobEuANOhAMYQWfFmaQrUNa1FiQ7DIcG+eP/B1zoVn0BqVJYLKoHhk3j2h1hOmU15iZZxeB5tHgxcMxd9rbXGIrWYFoE52I1VnAQ2RHKSlQQSlpj202HFh8MoBTkXaCCb7KGCfDqRiqBLhySgMFqMHKz5TlJaezV43WAWs03vgZE71fvhB7z263L9SiMfLvv6Xu8oPepuDXr9Y4KCiUFrG9pGFot7CfkACJQIZKrMV7frdKiK/viD5zWqvJqXnPpxYXIcIhmxu6oWQA6VHgDep53FAQg4Mo8GIczvdFutBYqjclMnjEdZ5M/z85/M2LeE4EnY6qBHk+2hhLocBYjlIlOOWIA3aRzLOebPSvhefUvEC9pQHEO8fzm/6fYblpcexpob+CI7Vfp22aR8aWhGqvBUo58wMCp5aaYKC+UdaTb+9pS0T45LuDk5/1dkUVzlsKqAT4B3uYYzchrUprddbr/jMXqdC1MNAeFY/dQ9oj7Lz2IJ5xtwoBVrJsCl5ZqXLFi34dmmbFWehRlva/Wic1kW2IBTyDqBGdyYNForeY=,iv:sHBQf3rWfyZ+7czO7if1P1Bn1cNNpBJgWHbMyZ09ELY=,tag:CYJWT70iji97A+fMlqYFwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d0piNHJPVGZSY2UydW44
            MVVIemlaOVY5eXFTWXNQWlFXbXB3TXI4TEVnCjExOHp0N0VRUlVGRWZURWRxY01Y
            ejlKWS92bWw0cklmcE54YVNxR25jdEEKLS0tIFJNS1F5Mk00ME5nVHYvRkxwRCsr
            SkpRbTRZRmswWTl5MjVnRGhKaEttZE0Ku7MPgWbW0B0lOIiCD5AeNYK+qlpVP6yt
            k62evquYzihuwiDSlylSKn3qLG6NNfMTwacqBMpLgG1DudumOePRbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T17:57:17Z"
    mac: ENC[AES256_GCM,data:U0cDss2kYpyu1Obm0T4h+hreqNX/a6fjkJaDd27bb0WwL3gUpn+Jxr2cPEYduf9ftcwfYwyW5XVclcgv7VdSak6INGgu79+xH9MlMROpQGtB8povr/sMHDc1DkX+4SKmJ10AA3gHJdTnskoruEmBH78zt3CxJYFtIndrlNq6XZM=,iv:aZpPP1Usg0njHhUMAojfCdM0hemcSAZLx08N+gQF+pY=,tag:drTp9Bl4wycaxPgMftL0XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
