apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:sGoB4QuIgODOM0mmyl48mWPTdupyTmHMXSCTXU2K1VaGDIE7hAjIRgbA8D9egv8IanZoQf7HJTfzx59R4/KvyXfVVcWp5OuSPW0JTP9V19od1USG9nnFgxaijyYCWMcKuozHTTWhWRFKQmLBlufQYhneBKXG1I8CjUnAQxV/Gc+uTTp8CXbjLe7qVqlBN/3CZkXdKlX3rgzJncBWLSEKe41auFqpuvFc6/uRJPkt+lZpVa/AtTtIuNIpCnP6NNs1Z8qtKluZ6sw7KecELcAUnrutsiWJfECbrc9UJ/bYlhaitOXDqy2PK6ccJSpBGpR59Retz4RJI0Yzx3hBYp+XaRoyG/+JgrZIP4OTObwC/M/cZgRY+pf4MrbZlV4I5XXslSKgFn+/T5ldsYoOXjzWg42FyPkS+MgZWKikSM+a9BA/TD3wpigpNR8uDw/Gc4TzA+WUcJPz+s8BYliDKonmuTEi9qeQFZsM3HO3CIgOtDKwZNAcZK+AacXFNsobOInNSWy9vFEdHcyrhddKXIFllWYpOuSpAN5e5f4n6Zbc6uJt74iPZdYXB22TQEuupKnZdS8fF7nMmBESGEmHafI5Q/4vmu5pGbvm2exW7RtHHH5Qnf26inqJ7xihhNRj3hbJkpOPfdU45Kk7P3q9s1foAdsIvWvtqs9NspOGfwX8BqWm5JzPlPmTiV/fqMT0CUYNQvm6nOq1VMM0N2V4VDMyVVkdyDXe4yi/2XPYP0RPjs/nOkYHSQSn+R5lwn/yWmdA674S1nie9pI2HEbpX95iUmuUuanApo5SdcYP5DC2yzGjW6qM6A0yzM+utNm5Zr7bLk6BsPJj2QwpBJx6NFGIOyLGiz0KYLItQl2Xo777R8T2OTiDOEVFzesh0cz9/U01l7+WecWyJUBYKWQHixsp6JecXnYtSHpxHIBW/1b/CoRcFLS+gygj7LzuA9d7rc19PLG/mpj0NTTo6aGDrlWtRzsCs7Usy7xvKKTv7bF8UYHsH0virnup6OgPeQ5XyG6faVNtkEtYpHmZ1ryPT5ABLnqEhdyirAXPMAUBInXc+NXtghShPlzoQaMb13IEeRJ7oZfjlgZnbbYru0myGHO1Bq8q6ypmzW2tayeHnPbhw+DGZD9WCM2Ph6FPa1K0GWcxrrQMl7bNWEYimuaCQJYr+UjvbIZEK2pLJXkiAat7lJ4AE6TC4UyZCcwYo7BWFIXeF9ReMAtSAfoaoDfIBnDigcmk2b6gn9xA2xZcw0DFJq20BQflEheA1fOoZFtltCxA4+Iv3gwl3+Af8JVoadM41v3evAjrMV9W7zbooyy/9QTTe8kx6/Et,iv:D8cX0vxwaBxZAxOtNbxvv1uxJJHwS+y2iYIliE+PJ/0=,tag:tFKFHCverCtVofRo61vH4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWmlKQ0VyMjl1dC9XekNX
            OE5QUXRHQTFvb0EyQjlBNVRiMXZORTlMWFJrCmptN1c2dU5melZMOTEzaWE2Wm9s
            NjdLNTBQbGp4ZllkRkdSVngvUVRtQjgKLS0tIG9SRVl4cytzcGVvZVZ2MkRNa0Z2
            NzdGOHdMMjN5R0prWjZwRlFEUFgvUncKsGROWzPDj6AsJ9hWjhwKq7LFqxscpq8W
            6AA5od4unNLGqugycoQmfvIbuod64l29A1Q49jA0iMJ2YOb+/vqNDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T23:57:54Z"
    mac: ENC[AES256_GCM,data:BsWEHVsLGgg6p8H/0s1STY5ixJ1R5zOTrAbfLZ8GjQOQSip2xxE1WVsdcmCx3TIoZeQUtGxmYOCP1qoSFlNNahBqMS/fbdhX/+64cletpGEElU8/e1pyvOvKMKhHSyURfaBt3BVDsPVqQxkS3U4Yj6z61UWEPK2l54rPNlMU+00=,iv:bEv6D9tBkAKCW+R7dJmnYJ7+AzWFYyqpiF4gbmNCjI4=,tag:P+0ZRmLXR+SmvxcTTIeX/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
