apiVersion: v1
kind: Secret
metadata:
    name: kube-actions-runner-values
    namespace: github-runners
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:zsP/6XBZbeb6FCNMPDfuwWOFNasjxrnmMsn1Wy6oiU4I8pHmhpxickf24VDv7K4XqfPCSSx+sZUtPNpHC5+P8etRhVaTaJN5lWiyk4dO1nYHyO0KqWO4WN+AxOBLr3pEB43tdvxIW6EWA5V+cH62TlzoQEOl2jAXy0iCd0Eh10Ul+9nydXXNj8qgMBUvb8umvXywGEVVhy+fcpWQG9aZvaq61xCI5kAcQxHu/dPkIPA/Cj8/EyJFxWUbLdk8wgDTjUbaNlKWJ3Uwdfs5tmKYU+e/8zljV4fkUYg1wLcPGOUmU3JtgCujYfgaVSc1zMqFzMmK+2jwuEJbnryu1bVLD2bEPu1HlBSzyngbl4WmPVYvX7KZbk4+1mfvtq+daaVLKOEAhBFanu/j1/9PJ33/Pt6accCjAtWtpGjc+eyGaBdHYXo+dHSgVNqp1UBBztigCfPBtzZerBq0/1cbE8Z5DsRPNv6vsfbqQ3yuVezRcChHv0OpLowgolvjxPB3y7wpBEifWbF8zIyWdGCwaQANP9FjVYpuNjFbtgSZz46mfk8HvbruTIxLqXXnWuo+rgg2JKYBtR/0r+s72ql/91lD4llrNpgmfk7YrsTKP+kZRSYovYtdBJLyzgBJhtlOltX7sBf9E3pXEc+gaJ1JnNNvjtlBW7RpSVWqR+66m5jnNw0GTHG0QcHH/pF9ryjuZMjHrbrcKE1Je+XMbb4aCPm5mWKX7oAZ3KIHMzMWrVNu5c2xPVeJ3TR/+U1P2ZYKXPtZ6/l43bk5AvDOqvBtxyLz4wUVALL2hEbUSDUvB/X2ne31lwC8RNFIXymA0JwnX3RxCAAMnFCJPZxNprpxbzZcrjHK7AdeCKNWiphROeQ/0uvgITcyBCZWWU6fyJb9juomDGHB4xnjio5CTuRXvGhdtmgBP7E6c25wxy1f85yAP8qi+kqfmE9CGaFqYx6fJjMqeQEFWiYINC1u2CRYAo617wXEV9j49h7HJFaoqwiec4j3485l05bickd5HYKCiqk3D/15+0M1Y/jb47GethGkO1tu3SOxtPTIKNLEa0PlQmEYrwVXXqzvBMcWeIQp+2wjf2bmZQpSdQ5aApoDu5A7w1pJ1Y9+Oi8tVS64yQSLQz6pptPunpecXsez1eX/BjKLeOVoaZGxuEeY2YGS5h7TVHzV39m0cyYdOZX0qu2aEEt5WYVhmT1ysC2hDc980ZdCcNASdy/m1qFPC+r2GlW4CvfG9FyeZjtWrGU5ab3RvbU0RhfoHLN10KUi7x/I0NrFvyqwNq5XFueAKK5dAoLje3i3R2A6c2SxusuIoWoKpNBrmZQgvhOKadTpvaF05AnhH4u6eX2zhiBx/QSQ,iv:civb7q9+3D7+1NnvPHQrJCwqP4dMK7y0qi2GcLghUFg=,tag:TMgJsrAAoWb9iw+xMxwsyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1va7h9cnqt2gfhvy0pj947wmmewlahvj9j4zyzfznkpp9erf8xawscgft7c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWHJNakdQZldEQmZ3M3pB
            aEUySUJjTjBtcXZGdjdobkdITmNwaFF4VFZvCmJDLzVtSXlvVno0YTNIVjQ1YkxM
            d0gwbUNFMWdDRnVvT3lFamkyRTExbmcKLS0tIDU2aHlmMmRmZEdmMFJOcHdGUVhP
            Ti9pQzByeFJrT0ptL1ZERU1PSlhaam8K6VRnoPWJDD/NqosQ1/XjUYpYhQxk1aQM
            VljbFTsa83CfviQSqrlRCD3e35F8oexjdhYNmwko2L3v70FkS0ViHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T01:03:33Z"
    mac: ENC[AES256_GCM,data:o7pcYWyYaaSpoMwJsQvCAw3VTkeRkj4VY8n7rJwT8m4q/YLLCpRvXU89BwZR/8oJsIr4j09e0ekh+u1kZxTocYspDkr7LC4t/1a0pTfiefMg93v2Q5j6ymg6/ex2TZKtJNOB6PitigJsiodvTHSXk2gEFVEduO8VxcsAGFhib34=,iv:/CQpIMF38jypYLpTBfjpDnTOrcaVu+Qujauk+E+45cw=,tag:8eaNvnNzRBcOvC9MaB6V2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|secrets|token|githubTokens?|.*Key|.*Auth.*)$
    version: 3.9.4
